### ISSUE TITLE
Suggestion: add handler for messages from naptime skill

### ISSUE THREAD

**Issue by domcross** [rekkitcwts/sleep-tracker-skill#1]
The [naptime skill](https://github.com/MycroftAI/skill-naptime) emits "recognizer_loop:sleep" and "recognizer_loop:wake_up" to the [message bus](https://mycroft.ai/documentation/message-bus/). 

Suggestion: add [message-handlers](https://mycroft.ai/documentation/message-bus/#connecting-message-handlers-within-a-mycroftskill) for above messages...

```
def initialize(self):  
    self.add_event('recognizer_loop:sleep', self.handle_tracker_sleep)  
    self.add_event('recognizer_loop:wake_up', self.handle_tracker_wakeup)
```

**Comment by rekkitcwts** [comment]
I'm confused; do these handlers trigger the sleep tracker when using the Naptime skill, if I'm not mistaken?

**Comment by domcross** [comment]
Yes, that is the idea.

**Comment by domcross** [comment]
See my PR: #2
